FROM openjdk:8
WORKDIR /work/project
ENV JAVA_OPTS "-server -Xms1G -Xmx1G"
ADD ./multi-datasource-springboot-start.jar /work/project/multi-datasource-springboot-start.jar
ADD ./config/ /work/project/config/
